services:
  postgres:
    image: postgres:16-alpine
    container_name: eventpro-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: eveniment
      POSTGRES_PASSWORD: eveniment_demo_2026
      POSTGRES_DB: eveniment_app
    volumes:
      - eventpro_postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eveniment"]
      interval: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventpro-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://eveniment:eveniment_demo_2026@postgres:5432/eveniment_app
      JWT_SECRET: f4931f63bec89c56b2774ab17ee54e10c7c937778a51cf60df0a24188b256fb2
      APP_URL: https://novabytecode.ro/eventpro
      CORS_ORIGINS: https://novabytecode.ro
      SMTP_HOST: ""
      SMTP_PORT: "587"
      SMTP_USER: ""
      SMTP_PASS: ""
      SMTP_FROM: no-reply@novabytecode.ro
    command: sh -c "npx prisma migrate deploy && node prisma/seed.js && npm start"
    networks:
      - internal
      - nova-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: /eventpro/api
        NEXT_PUBLIC_BASE_PATH: /eventpro
    container_name: eventpro-frontend
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: /eventpro/api
      NEXT_PUBLIC_BASE_PATH: /eventpro
    networks:
      - nova-net

volumes:
  eventpro_postgres_data:

networks:
  internal:
    driver: bridge
  nova-net:
    external: true
